In [3]:
from pathlib import Path 
import pandas as pd

data_dir = Path("../data")

mon = pd.read_csv(data_dir/'Monday.csv')
tue = pd.read_csv(data_dir/'Tuesday.csv')
wed = pd.read_csv(data_dir/'Wednesday.csv')
th_m = pd.read_csv(data_dir/'Thursday-m.csv')
th_af = pd.read_csv(data_dir/'Thursday-aft.csv')
fri_m = pd.read_csv(data_dir/'Friday-m.csv')
fri_af = pd.read_csv(data_dir/'Friday-aft.csv')
fri_af2 = pd.read_csv(data_dir/'Friday-aft2.csv')

mon.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [34]:
# df.info()

In [6]:
filename = [mon, tue, wed, th_m, th_af, fri_m, fri_af, fri_af2]

In [12]:
for file in filename:
    file.columns = file.columns.str.strip()

In [7]:
for i, file in enumerate(filename):
    print(f" {i} : {file['Label'].value_counts()}")

 0 : Label
BENIGN    529918
Name: count, dtype: int64
 1 : Label
BENIGN         432074
FTP-Patator      7938
SSH-Patator      5897
Name: count, dtype: int64
 2 : Label
BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name: count, dtype: int64
 3 : Label
BENIGN                        168186
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: int64
 4 : Label
BENIGN          288566
Infiltration        36
Name: count, dtype: int64
 5 : Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64
 6 : Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64
 7 : Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64

In [8]:
df = pd.concat(filename, ignore_index = True)

df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [10]:
# df.info()

In [13]:
df['Label'] = df['Label'].str.strip()

In [14]:
df['Label'].value_counts()

Label
BENIGN                        2273097
DoS Hulk                       231073
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [17]:
label_class = selected_classes = [
    'BENIGN',
    'FTP-Patator',
    'SSH-Patator',
    'DoS Hulk',
    'DoS GoldenEye',
    'DoS slowloris',
    'DoS Slowhttptest',
    'DDoS',
    'PortScan'
]

filtered_data = df[df['Label'].isin(selected_classes)]

In [25]:
merged_data = (filtered_data.groupby('Label', group_keys=False).sample(n=5000, random_state=42))

In [26]:
merged_data.groupby("Label")['Label'].count()

Label
BENIGN              5000
DDoS                5000
DoS GoldenEye       5000
DoS Hulk            5000
DoS Slowhttptest    5000
DoS slowloris       5000
FTP-Patator         5000
PortScan            5000
SSH-Patator         5000
Name: Label, dtype: int64

In [27]:
merged_data.to_csv(data_dir/'.csv')